[package]
name = "bmicalculator"
version = "0.1.1"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.8.0", package = "gtk4" }

[dependencies.adw]
package = "libadwaita"
version = "0.6"
features = ["v1_5"]
