name: "tagged-release"

on:
  push:
    tags:
      - "v*"
jobs:
  vendor:
    name: vendor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: dtolnay/rust-toolchain@stable
    - run: ./build-aux/dist-vendor.sh dist . && tar czf vendor.tar.gz dist
    - run:  sha256sum vendor.tar.gz > vendor.tar.gz.sha256sum
    - uses: actions/upload-artifact@v4
      with:
        name: vendor
        path: |
          *.tar.gz
          *.sha256sum
  publish-release:
    name: publish-release
    needs: [vendor]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Show files
      run: ls -R
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/*.tar.gz
          **/*.sha256sum